---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwtswaggerapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jwtswaggerapi
    spec:
      containers:
      - name: jwtswaggerapi
        image: nelsonrzjunior/jwt-swagger-api:1.0
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: jwtswaggerapi
---
apiVersion: v1
kind: Service
metadata:
  name: jwtswaggerapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: jwtswaggerapi
